// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBodyWeightLog(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['AddBodyWeightLog'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BackupDiagnostics() {
  return window['go']['app']['App']['BackupDiagnostics']();
}

export function CancelAPInvoice(arg1) {
  return window['go']['app']['App']['CancelAPInvoice'](arg1);
}

export function CancelARInvoice(arg1) {
  return window['go']['app']['App']['CancelARInvoice'](arg1);
}

export function CancelDeliveryReceipt(arg1) {
  return window['go']['app']['App']['CancelDeliveryReceipt'](arg1);
}

export function ChangePassword(arg1) {
  return window['go']['app']['App']['ChangePassword'](arg1);
}

export function ConfirmDeliveryOrder(arg1) {
  return window['go']['app']['App']['ConfirmDeliveryOrder'](arg1);
}

export function ConfirmDeliveryReceipt(arg1) {
  return window['go']['app']['App']['ConfirmDeliveryReceipt'](arg1);
}

export function CreateAPInvoice(arg1) {
  return window['go']['app']['App']['CreateAPInvoice'](arg1);
}

export function CreateAPPayment(arg1) {
  return window['go']['app']['App']['CreateAPPayment'](arg1);
}

export function CreateARInvoice(arg1) {
  return window['go']['app']['App']['CreateARInvoice'](arg1);
}

export function CreateBackup() {
  return window['go']['app']['App']['CreateBackup']();
}

export function CreateCollection(arg1) {
  return window['go']['app']['App']['CreateCollection'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['app']['App']['CreateCustomer'](arg1);
}

export function CreateDeliveryOrder(arg1) {
  return window['go']['app']['App']['CreateDeliveryOrder'](arg1);
}

export function CreateDeliveryReceipt(arg1) {
  return window['go']['app']['App']['CreateDeliveryReceipt'](arg1);
}

export function CreateFlock(arg1) {
  return window['go']['app']['App']['CreateFlock'](arg1);
}

export function CreateGLAccount(arg1) {
  return window['go']['app']['App']['CreateGLAccount'](arg1);
}

export function CreateItemCategory(arg1) {
  return window['go']['app']['App']['CreateItemCategory'](arg1);
}

export function CreateItemMaster(arg1) {
  return window['go']['app']['App']['CreateItemMaster'](arg1);
}

export function CreatePriceGroup(arg1) {
  return window['go']['app']['App']['CreatePriceGroup'](arg1);
}

export function CreatePurchase(arg1) {
  return window['go']['app']['App']['CreatePurchase'](arg1);
}

export function CreateSalesOrder(arg1) {
  return window['go']['app']['App']['CreateSalesOrder'](arg1);
}

export function CreateSupplier(arg1) {
  return window['go']['app']['App']['CreateSupplier'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['app']['App']['CreateUser'](arg1);
}

export function CreateVaccineSchedule(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateVaccineSchedule'](arg1, arg2, arg3, arg4);
}

export function DeleteAccountDetermination(arg1) {
  return window['go']['app']['App']['DeleteAccountDetermination'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteBodyWeightLog(arg1) {
  return window['go']['app']['App']['DeleteBodyWeightLog'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['app']['App']['DeleteCustomer'](arg1);
}

export function DeleteGLAccount(arg1) {
  return window['go']['app']['App']['DeleteGLAccount'](arg1);
}

export function DeleteItemCategory(arg1) {
  return window['go']['app']['App']['DeleteItemCategory'](arg1);
}

export function DeleteItemMaster(arg1) {
  return window['go']['app']['App']['DeleteItemMaster'](arg1);
}

export function DeletePriceGroup(arg1) {
  return window['go']['app']['App']['DeletePriceGroup'](arg1);
}

export function DeleteSupplier(arg1) {
  return window['go']['app']['App']['DeleteSupplier'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['app']['App']['DeleteUser'](arg1);
}

export function DownloadBackup(arg1) {
  return window['go']['app']['App']['DownloadBackup'](arg1);
}

export function GetAPInvoice(arg1) {
  return window['go']['app']['App']['GetAPInvoice'](arg1);
}

export function GetAPPayment(arg1) {
  return window['go']['app']['App']['GetAPPayment'](arg1);
}

export function GetARAgingReport() {
  return window['go']['app']['App']['GetARAgingReport']();
}

export function GetARInvoice(arg1) {
  return window['go']['app']['App']['GetARInvoice'](arg1);
}

export function GetAnalytics(arg1, arg2) {
  return window['go']['app']['App']['GetAnalytics'](arg1, arg2);
}

export function GetAuditLogs(arg1) {
  return window['go']['app']['App']['GetAuditLogs'](arg1);
}

export function GetBackupDir() {
  return window['go']['app']['App']['GetBackupDir']();
}

export function GetBackupHistory() {
  return window['go']['app']['App']['GetBackupHistory']();
}

export function GetBalanceSheet(arg1) {
  return window['go']['app']['App']['GetBalanceSheet'](arg1);
}

export function GetBodyWeightData(arg1) {
  return window['go']['app']['App']['GetBodyWeightData'](arg1);
}

export function GetChartOfAccounts() {
  return window['go']['app']['App']['GetChartOfAccounts']();
}

export function GetCollection(arg1) {
  return window['go']['app']['App']['GetCollection'](arg1);
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetCustomer(arg1) {
  return window['go']['app']['App']['GetCustomer'](arg1);
}

export function GetDailyLog(arg1) {
  return window['go']['app']['App']['GetDailyLog'](arg1);
}

export function GetDashboard() {
  return window['go']['app']['App']['GetDashboard']();
}

export function GetDeliveryOrder(arg1) {
  return window['go']['app']['App']['GetDeliveryOrder'](arg1);
}

export function GetDeliveryReceipt(arg1) {
  return window['go']['app']['App']['GetDeliveryReceipt'](arg1);
}

export function GetEggInventory() {
  return window['go']['app']['App']['GetEggInventory']();
}

export function GetFarmSettings() {
  return window['go']['app']['App']['GetFarmSettings']();
}

export function GetFlock(arg1) {
  return window['go']['app']['App']['GetFlock'](arg1);
}

export function GetFlocks() {
  return window['go']['app']['App']['GetFlocks']();
}

export function GetGLAccount(arg1) {
  return window['go']['app']['App']['GetGLAccount'](arg1);
}

export function GetGrowerLog(arg1) {
  return window['go']['app']['App']['GetGrowerLog'](arg1);
}

export function GetHouseHistory(arg1) {
  return window['go']['app']['App']['GetHouseHistory'](arg1);
}

export function GetItemCategory(arg1) {
  return window['go']['app']['App']['GetItemCategory'](arg1);
}

export function GetItemMaster(arg1) {
  return window['go']['app']['App']['GetItemMaster'](arg1);
}

export function GetJournalEntry(arg1) {
  return window['go']['app']['App']['GetJournalEntry'](arg1);
}

export function GetLayerHouses() {
  return window['go']['app']['App']['GetLayerHouses']();
}

export function GetPnL(arg1, arg2) {
  return window['go']['app']['App']['GetPnL'](arg1, arg2);
}

export function GetPostingEvents() {
  return window['go']['app']['App']['GetPostingEvents']();
}

export function GetPriceGroup(arg1) {
  return window['go']['app']['App']['GetPriceGroup'](arg1);
}

export function GetPurchase(arg1) {
  return window['go']['app']['App']['GetPurchase'](arg1);
}

export function GetSalesOrder(arg1) {
  return window['go']['app']['App']['GetSalesOrder'](arg1);
}

export function GetSupplier(arg1) {
  return window['go']['app']['App']['GetSupplier'](arg1);
}

export function ListAPInvoices(arg1, arg2) {
  return window['go']['app']['App']['ListAPInvoices'](arg1, arg2);
}

export function ListAPPayments() {
  return window['go']['app']['App']['ListAPPayments']();
}

export function ListARInvoices(arg1, arg2) {
  return window['go']['app']['App']['ListARInvoices'](arg1, arg2);
}

export function ListAccountDeterminations() {
  return window['go']['app']['App']['ListAccountDeterminations']();
}

export function ListCollections() {
  return window['go']['app']['App']['ListCollections']();
}

export function ListCustomers(arg1) {
  return window['go']['app']['App']['ListCustomers'](arg1);
}

export function ListDeliveryOrders(arg1) {
  return window['go']['app']['App']['ListDeliveryOrders'](arg1);
}

export function ListDeliveryReceipts(arg1) {
  return window['go']['app']['App']['ListDeliveryReceipts'](arg1);
}

export function ListFeedStocks() {
  return window['go']['app']['App']['ListFeedStocks']();
}

export function ListGLAccounts() {
  return window['go']['app']['App']['ListGLAccounts']();
}

export function ListInventory() {
  return window['go']['app']['App']['ListInventory']();
}

export function ListItemCategories() {
  return window['go']['app']['App']['ListItemCategories']();
}

export function ListItemMasters() {
  return window['go']['app']['App']['ListItemMasters']();
}

export function ListJournalEntries(arg1, arg2) {
  return window['go']['app']['App']['ListJournalEntries'](arg1, arg2);
}

export function ListPaymentMethodAccounts() {
  return window['go']['app']['App']['ListPaymentMethodAccounts']();
}

export function ListPriceGroups(arg1) {
  return window['go']['app']['App']['ListPriceGroups'](arg1);
}

export function ListPurchases() {
  return window['go']['app']['App']['ListPurchases']();
}

export function ListSalesOrders() {
  return window['go']['app']['App']['ListSalesOrders']();
}

export function ListSuppliers(arg1) {
  return window['go']['app']['App']['ListSuppliers'](arg1);
}

export function ListUsers() {
  return window['go']['app']['App']['ListUsers']();
}

export function ListVaccineSchedules(arg1) {
  return window['go']['app']['App']['ListVaccineSchedules'](arg1);
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function MarkVaccineComplete(arg1) {
  return window['go']['app']['App']['MarkVaccineComplete'](arg1);
}

export function PostManualJournalEntry(arg1) {
  return window['go']['app']['App']['PostManualJournalEntry'](arg1);
}

export function RecordDailyLog(arg1) {
  return window['go']['app']['App']['RecordDailyLog'](arg1);
}

export function RecordGrowerLog(arg1) {
  return window['go']['app']['App']['RecordGrowerLog'](arg1);
}

export function RetireFlock(arg1) {
  return window['go']['app']['App']['RetireFlock'](arg1);
}

export function ReverseJournalEntry(arg1) {
  return window['go']['app']['App']['ReverseJournalEntry'](arg1);
}

export function SetPermissions(arg1) {
  return window['go']['app']['App']['SetPermissions'](arg1);
}

export function TransferFlock(arg1) {
  return window['go']['app']['App']['TransferFlock'](arg1);
}

export function UpdateBodyWeightLog(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateBodyWeightLog'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['app']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateDailyLog(arg1, arg2) {
  return window['go']['app']['App']['UpdateDailyLog'](arg1, arg2);
}

export function UpdateFarmSetting(arg1, arg2) {
  return window['go']['app']['App']['UpdateFarmSetting'](arg1, arg2);
}

export function UpdateFarmSettings(arg1) {
  return window['go']['app']['App']['UpdateFarmSettings'](arg1);
}

export function UpdateFlock(arg1) {
  return window['go']['app']['App']['UpdateFlock'](arg1);
}

export function UpdateGLAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateGLAccount'](arg1, arg2);
}

export function UpdateGrowerLog(arg1, arg2) {
  return window['go']['app']['App']['UpdateGrowerLog'](arg1, arg2);
}

export function UpdateItemCategory(arg1, arg2) {
  return window['go']['app']['App']['UpdateItemCategory'](arg1, arg2);
}

export function UpdateItemMaster(arg1, arg2) {
  return window['go']['app']['App']['UpdateItemMaster'](arg1, arg2);
}

export function UpdatePriceGroup(arg1, arg2) {
  return window['go']['app']['App']['UpdatePriceGroup'](arg1, arg2);
}

export function UpdatePurchase(arg1, arg2) {
  return window['go']['app']['App']['UpdatePurchase'](arg1, arg2);
}

export function UpdateSupplier(arg1, arg2) {
  return window['go']['app']['App']['UpdateSupplier'](arg1, arg2);
}

export function UpdateUser(arg1) {
  return window['go']['app']['App']['UpdateUser'](arg1);
}

export function UpsertAccountDetermination(arg1) {
  return window['go']['app']['App']['UpsertAccountDetermination'](arg1);
}

export function UpsertPaymentMethodAccount(arg1) {
  return window['go']['app']['App']['UpsertPaymentMethodAccount'](arg1);
}

export function UpsertPriceGroupItem(arg1) {
  return window['go']['app']['App']['UpsertPriceGroupItem'](arg1);
}

export function VoidSalesOrder(arg1) {
  return window['go']['app']['App']['VoidSalesOrder'](arg1);
}
