// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {production} from '../models';
import {models} from '../models';
import {inventory} from '../models';
import {purchasing} from '../models';

export function ApproveSupplier(arg1:number):Promise<handlers.Response>;

export function BackupDiagnostics():Promise<handlers.Response>;

export function CancelAPInvoice(arg1:number):Promise<handlers.Response>;

export function CancelAPPayment(arg1:number):Promise<handlers.Response>;

export function CancelARInvoice(arg1:number):Promise<handlers.Response>;

export function CancelCollection(arg1:number):Promise<handlers.Response>;

export function CancelDeliveryOrder(arg1:number):Promise<handlers.Response>;

export function CancelDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function CancelGoodsIssue(arg1:number):Promise<handlers.Response>;

export function CancelGoodsReceipt(arg1:number):Promise<handlers.Response>;

export function CancelMillingOrder(arg1:number):Promise<handlers.Response>;

export function CancelPurchaseHeader(arg1:number):Promise<handlers.Response>;

export function CancelSalesOrder(arg1:number):Promise<handlers.Response>;

export function CancelWorkOrder(arg1:number):Promise<handlers.Response>;

export function ChangePassword(arg1:handlers.ChangePasswordRequest):Promise<handlers.Response>;

export function CloseWorkOrder(arg1:number,arg2:number,arg3:number):Promise<handlers.Response>;

export function CommitMasterDataImport(arg1:string,arg2:string):Promise<handlers.Response>;

export function CompleteMillingOrder(arg1:number,arg2:production.CompleteMillingRequest):Promise<handlers.Response>;

export function ComputeWHT(arg1:handlers.ComputeWHTRequest):Promise<handlers.Response>;

export function ConfirmDeliveryOrder(arg1:number):Promise<handlers.Response>;

export function ConfirmDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function CreateAPInvoice(arg1:handlers.CreateAPInvoiceRequest):Promise<handlers.Response>;

export function CreateAPPayment(arg1:handlers.CreateAPPaymentRequest):Promise<handlers.Response>;

export function CreateARInvoice(arg1:handlers.CreateARInvoiceRequest):Promise<handlers.Response>;

export function CreateBackup():Promise<handlers.Response>;

export function CreateCollection(arg1:handlers.CreateCollectionRequest):Promise<handlers.Response>;

export function CreateCustomer(arg1:models.Customer):Promise<handlers.Response>;

export function CreateDeliveryOrder(arg1:handlers.CreateDeliveryOrderRequest):Promise<handlers.Response>;

export function CreateDeliveryReceipt(arg1:handlers.CreateDeliveryReceiptRequest):Promise<handlers.Response>;

export function CreateFixedAsset(arg1:handlers.CreateFixedAssetRequest):Promise<handlers.Response>;

export function CreateGLAccount(arg1:handlers.CreateGLAccountRequest):Promise<handlers.Response>;

export function CreateGoodsIssue(arg1:inventory.CreateGoodsIssueRequest):Promise<handlers.Response>;

export function CreateGoodsReceipt(arg1:inventory.CreateGoodsReceiptRequest):Promise<handlers.Response>;

export function CreateItemCategory(arg1:models.OITB):Promise<handlers.Response>;

export function CreateItemMaster(arg1:models.OITM):Promise<handlers.Response>;

export function CreateMillingOrder(arg1:production.CreateMillingOrderRequest):Promise<handlers.Response>;

export function CreatePriceGroup(arg1:models.PriceGroup):Promise<handlers.Response>;

export function CreatePurchaseHeader(arg1:purchasing.CreatePurchaseParams):Promise<handlers.Response>;

export function CreateSalesOrder(arg1:handlers.CreateSalesOrderRequest):Promise<handlers.Response>;

export function CreateSupplier(arg1:models.Supplier):Promise<handlers.Response>;

export function CreateUoMGroup(arg1:inventory.CreateUoMGroupRequest):Promise<handlers.Response>;

export function CreateUoMMaster(arg1:models.UoMMaster):Promise<handlers.Response>;

export function CreateUser(arg1:handlers.CreateUserRequest):Promise<handlers.Response>;

export function CreateWarehouse(arg1:models.OWHS):Promise<handlers.Response>;

export function CreateWorkOrder(arg1:production.CreateWORequest):Promise<handlers.Response>;

export function DeleteAccountDetermination(arg1:number):Promise<handlers.Response>;

export function DeleteBOM(arg1:string):Promise<handlers.Response>;

export function DeleteBackup(arg1:string):Promise<handlers.Response>;

export function DeleteCustomer(arg1:number):Promise<handlers.Response>;

export function DeleteGLAccount(arg1:number):Promise<handlers.Response>;

export function DeleteItemCategory(arg1:number):Promise<handlers.Response>;

export function DeleteItemMaster(arg1:number):Promise<handlers.Response>;

export function DeleteItemUoMPrice(arg1:string,arg2:number):Promise<handlers.Response>;

export function DeletePriceGroup(arg1:number):Promise<handlers.Response>;

export function DeleteSpecialPrice(arg1:string,arg2:string):Promise<handlers.Response>;

export function DeleteSupplier(arg1:number):Promise<handlers.Response>;

export function DeleteUoMGroup(arg1:number):Promise<handlers.Response>;

export function DeleteUoMMaster(arg1:number):Promise<handlers.Response>;

export function DeleteUser(arg1:number):Promise<handlers.Response>;

export function DemoLogin():Promise<handlers.Response>;

export function DisposeAsset(arg1:handlers.DisposeAssetRequest):Promise<handlers.Response>;

export function DownloadBackup(arg1:string):Promise<handlers.Response>;

export function DownloadImportTemplate(arg1:string):Promise<handlers.Response>;

export function ExportBalanceSheetExcel(arg1:string):Promise<handlers.Response>;

export function ExportPnLExcel(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetAPAgingReport():Promise<handlers.Response>;

export function GetAPInvoice(arg1:number):Promise<handlers.Response>;

export function GetAPPayment(arg1:number):Promise<handlers.Response>;

export function GetARAgingReport():Promise<handlers.Response>;

export function GetARInvoice(arg1:number):Promise<handlers.Response>;

export function GetAnalytics(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetAuditLogs(arg1:number):Promise<handlers.Response>;

export function GetBOM(arg1:string):Promise<handlers.Response>;

export function GetBackupDir():Promise<handlers.Response>;

export function GetBackupHistory():Promise<handlers.Response>;

export function GetBalanceSheet(arg1:string):Promise<handlers.Response>;

export function GetCashFlowStatement(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetCollection(arg1:number):Promise<handlers.Response>;

export function GetCurrentUser():Promise<handlers.Response>;

export function GetCustomer(arg1:number):Promise<handlers.Response>;

export function GetDeliveryOrder(arg1:number):Promise<handlers.Response>;

export function GetDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function GetDepreciationSchedule(arg1:number):Promise<handlers.Response>;

export function GetFarmSettings():Promise<handlers.Response>;

export function GetFixedAsset(arg1:number):Promise<handlers.Response>;

export function GetForm0619E(arg1:number,arg2:number):Promise<handlers.Response>;

export function GetForm1601EQ(arg1:number,arg2:number):Promise<handlers.Response>;

export function GetForm2307(arg1:number,arg2:number,arg3:number,arg4:string):Promise<handlers.Response>;

export function GetGLAccount(arg1:number):Promise<handlers.Response>;

export function GetGLAccounts():Promise<handlers.Response>;

export function GetGoodsIssue(arg1:number):Promise<handlers.Response>;

export function GetGoodsReceipt(arg1:number):Promise<handlers.Response>;

export function GetInventoryMovementReport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<handlers.Response>;

export function GetInventoryValuationReport(arg1:string,arg2:string,arg3:number):Promise<handlers.Response>;

export function GetItemCategory(arg1:number):Promise<handlers.Response>;

export function GetItemMaster(arg1:number):Promise<handlers.Response>;

export function GetItemUoMMapping(arg1:string):Promise<handlers.Response>;

export function GetItemUoMPrices(arg1:string):Promise<handlers.Response>;

export function GetItemWarehouseStock(arg1:string):Promise<handlers.Response>;

export function GetJournalEntry(arg1:number):Promise<handlers.Response>;

export function GetMillingOrder(arg1:number):Promise<handlers.Response>;

export function GetMillingYieldReport():Promise<handlers.Response>;

export function GetNextPONumber():Promise<handlers.Response>;

export function GetPnL(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetPostingEvents():Promise<handlers.Response>;

export function GetPriceGroup(arg1:number):Promise<handlers.Response>;

export function GetPurchaseHeader(arg1:number):Promise<handlers.Response>;

export function GetSalesOrder(arg1:number):Promise<handlers.Response>;

export function GetSupplier(arg1:number):Promise<handlers.Response>;

export function GetTrialBalance(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetUoMGroup(arg1:number):Promise<handlers.Response>;

export function GetUoMMaster(arg1:number):Promise<handlers.Response>;

export function GetWarehouse(arg1:string):Promise<handlers.Response>;

export function GetWarehouseStock(arg1:string):Promise<handlers.Response>;

export function GetWorkOrder(arg1:number):Promise<handlers.Response>;

export function ListAPInvoices(arg1:any,arg2:string):Promise<handlers.Response>;

export function ListAPPayments():Promise<handlers.Response>;

export function ListARInvoices(arg1:any,arg2:string):Promise<handlers.Response>;

export function ListAccountDeterminations():Promise<handlers.Response>;

export function ListAllWarehouseStock():Promise<handlers.Response>;

export function ListBOMs():Promise<handlers.Response>;

export function ListCollections():Promise<handlers.Response>;

export function ListCustomers(arg1:boolean):Promise<handlers.Response>;

export function ListDeliveryOrders(arg1:number):Promise<handlers.Response>;

export function ListDeliveryReceipts(arg1:number):Promise<handlers.Response>;

export function ListFixedAssets():Promise<handlers.Response>;

export function ListGLAccounts():Promise<handlers.Response>;

export function ListGoodsIssues():Promise<handlers.Response>;

export function ListGoodsReceipts():Promise<handlers.Response>;

export function ListInventoryItems():Promise<handlers.Response>;

export function ListItemCategories():Promise<handlers.Response>;

export function ListItemCategoriesForModule(arg1:string):Promise<handlers.Response>;

export function ListItemMasters():Promise<handlers.Response>;

export function ListItemPrices(arg1:string):Promise<handlers.Response>;

export function ListJournalEntries(arg1:string,arg2:number):Promise<handlers.Response>;

export function ListMillingOrders():Promise<handlers.Response>;

export function ListOIVL(arg1:string):Promise<handlers.Response>;

export function ListOpenPurchaseHeaders(arg1:number):Promise<handlers.Response>;

export function ListPaymentMethodAccounts():Promise<handlers.Response>;

export function ListPriceGroups(arg1:boolean):Promise<handlers.Response>;

export function ListProductionItems():Promise<handlers.Response>;

export function ListPurchaseHeaders():Promise<handlers.Response>;

export function ListPurchasingItems():Promise<handlers.Response>;

export function ListPurchasingLookup(arg1:string):Promise<handlers.Response>;

export function ListSalesItems():Promise<handlers.Response>;

export function ListSalesOrders():Promise<handlers.Response>;

export function ListSpecialPrices(arg1:string):Promise<handlers.Response>;

export function ListSuppliers(arg1:boolean):Promise<handlers.Response>;

export function ListSuppliersWithWHT(arg1:number):Promise<handlers.Response>;

export function ListUoMGroups():Promise<handlers.Response>;

export function ListUoMMasters():Promise<handlers.Response>;

export function ListUsers():Promise<handlers.Response>;

export function ListWHTEntries(arg1:number,arg2:number):Promise<handlers.Response>;

export function ListWarehouses():Promise<handlers.Response>;

export function ListWorkOrders():Promise<handlers.Response>;

export function Login(arg1:handlers.LoginRequest):Promise<handlers.Response>;

export function Logout():Promise<handlers.Response>;

export function PostManualJournalEntry(arg1:handlers.ManualJERequest):Promise<handlers.Response>;

export function PreviewMasterDataImport(arg1:string):Promise<handlers.Response>;

export function RejectSupplier(arg1:number):Promise<handlers.Response>;

export function ReleaseWorkOrder(arg1:number):Promise<handlers.Response>;

export function ReverseJournalEntry(arg1:number):Promise<handlers.Response>;

export function RunDepreciation(arg1:handlers.RunDepreciationRequest):Promise<handlers.Response>;

export function SetPermissions(arg1:handlers.SetPermissionsRequest):Promise<handlers.Response>;

export function StartMillingOrder(arg1:number):Promise<handlers.Response>;

export function SubmitSalesOrder(arg1:number):Promise<handlers.Response>;

export function UpdateCustomer(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateFarmSetting(arg1:string,arg2:string):Promise<handlers.Response>;

export function UpdateFarmSettings(arg1:Record<string, string>):Promise<handlers.Response>;

export function UpdateFixedAsset(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateGLAccount(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateItemCategory(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateItemMaster(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateOITWMinMax(arg1:string,arg2:string,arg3:number,arg4:number):Promise<handlers.Response>;

export function UpdatePriceGroup(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateSalesOrder(arg1:number,arg2:handlers.UpdateSalesOrderRequest):Promise<handlers.Response>;

export function UpdateSupplier(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateUoMGroup(arg1:number,arg2:string,arg3:string,arg4:number,arg5:Array<inventory.UoMGroupLineInput>):Promise<handlers.Response>;

export function UpdateUoMMaster(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateUser(arg1:handlers.UpdateUserRequest):Promise<handlers.Response>;

export function UpdateWarehouse(arg1:string,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpsertAccountDetermination(arg1:handlers.UpsertAccountDeterminationRequest):Promise<handlers.Response>;

export function UpsertBOM(arg1:models.ProductTree):Promise<handlers.Response>;

export function UpsertItemPrice(arg1:handlers.UpsertItemPriceRequest):Promise<handlers.Response>;

export function UpsertItemUoMPrice(arg1:handlers.UpsertItemUoMPriceRequest):Promise<handlers.Response>;

export function UpsertPaymentMethodAccount(arg1:handlers.UpsertPaymentMethodAccountRequest):Promise<handlers.Response>;

export function UpsertPriceGroupItem(arg1:handlers.UpsertPriceGroupItemRequest):Promise<handlers.Response>;

export function UpsertSpecialPrice(arg1:models.OSPP):Promise<handlers.Response>;

export function VoidSalesOrder(arg1:number):Promise<handlers.Response>;
