// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveSupplier(arg1) {
  return window['go']['app']['App']['ApproveSupplier'](arg1);
}

export function BackupDiagnostics() {
  return window['go']['app']['App']['BackupDiagnostics']();
}

export function CancelAPInvoice(arg1) {
  return window['go']['app']['App']['CancelAPInvoice'](arg1);
}

export function CancelAPPayment(arg1) {
  return window['go']['app']['App']['CancelAPPayment'](arg1);
}

export function CancelARInvoice(arg1) {
  return window['go']['app']['App']['CancelARInvoice'](arg1);
}

export function CancelCollection(arg1) {
  return window['go']['app']['App']['CancelCollection'](arg1);
}

export function CancelDeliveryOrder(arg1) {
  return window['go']['app']['App']['CancelDeliveryOrder'](arg1);
}

export function CancelDeliveryReceipt(arg1) {
  return window['go']['app']['App']['CancelDeliveryReceipt'](arg1);
}

export function CancelGoodsIssue(arg1) {
  return window['go']['app']['App']['CancelGoodsIssue'](arg1);
}

export function CancelGoodsReceipt(arg1) {
  return window['go']['app']['App']['CancelGoodsReceipt'](arg1);
}

export function CancelMillingOrder(arg1) {
  return window['go']['app']['App']['CancelMillingOrder'](arg1);
}

export function CancelPurchaseHeader(arg1) {
  return window['go']['app']['App']['CancelPurchaseHeader'](arg1);
}

export function CancelSalesOrder(arg1) {
  return window['go']['app']['App']['CancelSalesOrder'](arg1);
}

export function CancelWorkOrder(arg1) {
  return window['go']['app']['App']['CancelWorkOrder'](arg1);
}

export function ChangePassword(arg1) {
  return window['go']['app']['App']['ChangePassword'](arg1);
}

export function CloseWorkOrder(arg1, arg2, arg3) {
  return window['go']['app']['App']['CloseWorkOrder'](arg1, arg2, arg3);
}

export function CommitMasterDataImport(arg1, arg2) {
  return window['go']['app']['App']['CommitMasterDataImport'](arg1, arg2);
}

export function CompleteMillingOrder(arg1, arg2) {
  return window['go']['app']['App']['CompleteMillingOrder'](arg1, arg2);
}

export function ComputeWHT(arg1) {
  return window['go']['app']['App']['ComputeWHT'](arg1);
}

export function ConfirmDeliveryOrder(arg1) {
  return window['go']['app']['App']['ConfirmDeliveryOrder'](arg1);
}

export function ConfirmDeliveryReceipt(arg1) {
  return window['go']['app']['App']['ConfirmDeliveryReceipt'](arg1);
}

export function CreateAPInvoice(arg1) {
  return window['go']['app']['App']['CreateAPInvoice'](arg1);
}

export function CreateAPPayment(arg1) {
  return window['go']['app']['App']['CreateAPPayment'](arg1);
}

export function CreateARInvoice(arg1) {
  return window['go']['app']['App']['CreateARInvoice'](arg1);
}

export function CreateBackup() {
  return window['go']['app']['App']['CreateBackup']();
}

export function CreateCollection(arg1) {
  return window['go']['app']['App']['CreateCollection'](arg1);
}

export function CreateCustomer(arg1) {
  return window['go']['app']['App']['CreateCustomer'](arg1);
}

export function CreateDeliveryOrder(arg1) {
  return window['go']['app']['App']['CreateDeliveryOrder'](arg1);
}

export function CreateDeliveryReceipt(arg1) {
  return window['go']['app']['App']['CreateDeliveryReceipt'](arg1);
}

export function CreateFixedAsset(arg1) {
  return window['go']['app']['App']['CreateFixedAsset'](arg1);
}

export function CreateGLAccount(arg1) {
  return window['go']['app']['App']['CreateGLAccount'](arg1);
}

export function CreateGoodsIssue(arg1) {
  return window['go']['app']['App']['CreateGoodsIssue'](arg1);
}

export function CreateGoodsReceipt(arg1) {
  return window['go']['app']['App']['CreateGoodsReceipt'](arg1);
}

export function CreateItemCategory(arg1) {
  return window['go']['app']['App']['CreateItemCategory'](arg1);
}

export function CreateItemMaster(arg1) {
  return window['go']['app']['App']['CreateItemMaster'](arg1);
}

export function CreateMillingOrder(arg1) {
  return window['go']['app']['App']['CreateMillingOrder'](arg1);
}

export function CreatePriceGroup(arg1) {
  return window['go']['app']['App']['CreatePriceGroup'](arg1);
}

export function CreatePurchaseHeader(arg1) {
  return window['go']['app']['App']['CreatePurchaseHeader'](arg1);
}

export function CreateSalesOrder(arg1) {
  return window['go']['app']['App']['CreateSalesOrder'](arg1);
}

export function CreateSupplier(arg1) {
  return window['go']['app']['App']['CreateSupplier'](arg1);
}

export function CreateUoMGroup(arg1) {
  return window['go']['app']['App']['CreateUoMGroup'](arg1);
}

export function CreateUoMMaster(arg1) {
  return window['go']['app']['App']['CreateUoMMaster'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['app']['App']['CreateUser'](arg1);
}

export function CreateWarehouse(arg1) {
  return window['go']['app']['App']['CreateWarehouse'](arg1);
}

export function CreateWorkOrder(arg1) {
  return window['go']['app']['App']['CreateWorkOrder'](arg1);
}

export function DeleteAccountDetermination(arg1) {
  return window['go']['app']['App']['DeleteAccountDetermination'](arg1);
}

export function DeleteBOM(arg1) {
  return window['go']['app']['App']['DeleteBOM'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['app']['App']['DeleteCustomer'](arg1);
}

export function DeleteGLAccount(arg1) {
  return window['go']['app']['App']['DeleteGLAccount'](arg1);
}

export function DeleteItemCategory(arg1) {
  return window['go']['app']['App']['DeleteItemCategory'](arg1);
}

export function DeleteItemMaster(arg1) {
  return window['go']['app']['App']['DeleteItemMaster'](arg1);
}

export function DeleteItemUoMPrice(arg1, arg2) {
  return window['go']['app']['App']['DeleteItemUoMPrice'](arg1, arg2);
}

export function DeletePriceGroup(arg1) {
  return window['go']['app']['App']['DeletePriceGroup'](arg1);
}

export function DeleteSpecialPrice(arg1, arg2) {
  return window['go']['app']['App']['DeleteSpecialPrice'](arg1, arg2);
}

export function DeleteSupplier(arg1) {
  return window['go']['app']['App']['DeleteSupplier'](arg1);
}

export function DeleteUoMGroup(arg1) {
  return window['go']['app']['App']['DeleteUoMGroup'](arg1);
}

export function DeleteUoMMaster(arg1) {
  return window['go']['app']['App']['DeleteUoMMaster'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['app']['App']['DeleteUser'](arg1);
}

export function DemoLogin() {
  return window['go']['app']['App']['DemoLogin']();
}

export function DisposeAsset(arg1) {
  return window['go']['app']['App']['DisposeAsset'](arg1);
}

export function DownloadBackup(arg1) {
  return window['go']['app']['App']['DownloadBackup'](arg1);
}

export function DownloadImportTemplate(arg1) {
  return window['go']['app']['App']['DownloadImportTemplate'](arg1);
}

export function ExportBalanceSheetExcel(arg1) {
  return window['go']['app']['App']['ExportBalanceSheetExcel'](arg1);
}

export function ExportPnLExcel(arg1, arg2) {
  return window['go']['app']['App']['ExportPnLExcel'](arg1, arg2);
}

export function GetAPAgingReport() {
  return window['go']['app']['App']['GetAPAgingReport']();
}

export function GetAPInvoice(arg1) {
  return window['go']['app']['App']['GetAPInvoice'](arg1);
}

export function GetAPPayment(arg1) {
  return window['go']['app']['App']['GetAPPayment'](arg1);
}

export function GetARAgingReport() {
  return window['go']['app']['App']['GetARAgingReport']();
}

export function GetARInvoice(arg1) {
  return window['go']['app']['App']['GetARInvoice'](arg1);
}

export function GetAnalytics(arg1, arg2) {
  return window['go']['app']['App']['GetAnalytics'](arg1, arg2);
}

export function GetAuditLogs(arg1) {
  return window['go']['app']['App']['GetAuditLogs'](arg1);
}

export function GetBOM(arg1) {
  return window['go']['app']['App']['GetBOM'](arg1);
}

export function GetBackupDir() {
  return window['go']['app']['App']['GetBackupDir']();
}

export function GetBackupHistory() {
  return window['go']['app']['App']['GetBackupHistory']();
}

export function GetBalanceSheet(arg1) {
  return window['go']['app']['App']['GetBalanceSheet'](arg1);
}

export function GetCashFlowStatement(arg1, arg2) {
  return window['go']['app']['App']['GetCashFlowStatement'](arg1, arg2);
}

export function GetCollection(arg1) {
  return window['go']['app']['App']['GetCollection'](arg1);
}

export function GetCurrentUser() {
  return window['go']['app']['App']['GetCurrentUser']();
}

export function GetCustomer(arg1) {
  return window['go']['app']['App']['GetCustomer'](arg1);
}

export function GetDeliveryOrder(arg1) {
  return window['go']['app']['App']['GetDeliveryOrder'](arg1);
}

export function GetDeliveryReceipt(arg1) {
  return window['go']['app']['App']['GetDeliveryReceipt'](arg1);
}

export function GetDepreciationSchedule(arg1) {
  return window['go']['app']['App']['GetDepreciationSchedule'](arg1);
}

export function GetFarmSettings() {
  return window['go']['app']['App']['GetFarmSettings']();
}

export function GetFixedAsset(arg1) {
  return window['go']['app']['App']['GetFixedAsset'](arg1);
}

export function GetForm0619E(arg1, arg2) {
  return window['go']['app']['App']['GetForm0619E'](arg1, arg2);
}

export function GetForm1601EQ(arg1, arg2) {
  return window['go']['app']['App']['GetForm1601EQ'](arg1, arg2);
}

export function GetForm2307(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetForm2307'](arg1, arg2, arg3, arg4);
}

export function GetGLAccount(arg1) {
  return window['go']['app']['App']['GetGLAccount'](arg1);
}

export function GetGLAccounts() {
  return window['go']['app']['App']['GetGLAccounts']();
}

export function GetGoodsIssue(arg1) {
  return window['go']['app']['App']['GetGoodsIssue'](arg1);
}

export function GetGoodsReceipt(arg1) {
  return window['go']['app']['App']['GetGoodsReceipt'](arg1);
}

export function GetInventoryMovementReport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['GetInventoryMovementReport'](arg1, arg2, arg3, arg4, arg5);
}

export function GetInventoryValuationReport(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetInventoryValuationReport'](arg1, arg2, arg3);
}

export function GetItemCategory(arg1) {
  return window['go']['app']['App']['GetItemCategory'](arg1);
}

export function GetItemMaster(arg1) {
  return window['go']['app']['App']['GetItemMaster'](arg1);
}

export function GetItemUoMMapping(arg1) {
  return window['go']['app']['App']['GetItemUoMMapping'](arg1);
}

export function GetItemUoMPrices(arg1) {
  return window['go']['app']['App']['GetItemUoMPrices'](arg1);
}

export function GetItemWarehouseStock(arg1) {
  return window['go']['app']['App']['GetItemWarehouseStock'](arg1);
}

export function GetJournalEntry(arg1) {
  return window['go']['app']['App']['GetJournalEntry'](arg1);
}

export function GetMillingOrder(arg1) {
  return window['go']['app']['App']['GetMillingOrder'](arg1);
}

export function GetMillingYieldReport() {
  return window['go']['app']['App']['GetMillingYieldReport']();
}

export function GetNextPONumber() {
  return window['go']['app']['App']['GetNextPONumber']();
}

export function GetPnL(arg1, arg2) {
  return window['go']['app']['App']['GetPnL'](arg1, arg2);
}

export function GetPostingEvents() {
  return window['go']['app']['App']['GetPostingEvents']();
}

export function GetPriceGroup(arg1) {
  return window['go']['app']['App']['GetPriceGroup'](arg1);
}

export function GetPurchaseHeader(arg1) {
  return window['go']['app']['App']['GetPurchaseHeader'](arg1);
}

export function GetSalesOrder(arg1) {
  return window['go']['app']['App']['GetSalesOrder'](arg1);
}

export function GetSupplier(arg1) {
  return window['go']['app']['App']['GetSupplier'](arg1);
}

export function GetTrialBalance(arg1, arg2) {
  return window['go']['app']['App']['GetTrialBalance'](arg1, arg2);
}

export function GetUoMGroup(arg1) {
  return window['go']['app']['App']['GetUoMGroup'](arg1);
}

export function GetUoMMaster(arg1) {
  return window['go']['app']['App']['GetUoMMaster'](arg1);
}

export function GetWarehouse(arg1) {
  return window['go']['app']['App']['GetWarehouse'](arg1);
}

export function GetWarehouseStock(arg1) {
  return window['go']['app']['App']['GetWarehouseStock'](arg1);
}

export function GetWorkOrder(arg1) {
  return window['go']['app']['App']['GetWorkOrder'](arg1);
}

export function ListAPInvoices(arg1, arg2) {
  return window['go']['app']['App']['ListAPInvoices'](arg1, arg2);
}

export function ListAPPayments() {
  return window['go']['app']['App']['ListAPPayments']();
}

export function ListARInvoices(arg1, arg2) {
  return window['go']['app']['App']['ListARInvoices'](arg1, arg2);
}

export function ListAccountDeterminations() {
  return window['go']['app']['App']['ListAccountDeterminations']();
}

export function ListAllWarehouseStock() {
  return window['go']['app']['App']['ListAllWarehouseStock']();
}

export function ListBOMs() {
  return window['go']['app']['App']['ListBOMs']();
}

export function ListCollections() {
  return window['go']['app']['App']['ListCollections']();
}

export function ListCustomers(arg1) {
  return window['go']['app']['App']['ListCustomers'](arg1);
}

export function ListDeliveryOrders(arg1) {
  return window['go']['app']['App']['ListDeliveryOrders'](arg1);
}

export function ListDeliveryReceipts(arg1) {
  return window['go']['app']['App']['ListDeliveryReceipts'](arg1);
}

export function ListFixedAssets() {
  return window['go']['app']['App']['ListFixedAssets']();
}

export function ListGLAccounts() {
  return window['go']['app']['App']['ListGLAccounts']();
}

export function ListGoodsIssues() {
  return window['go']['app']['App']['ListGoodsIssues']();
}

export function ListGoodsReceipts() {
  return window['go']['app']['App']['ListGoodsReceipts']();
}

export function ListInventoryItems() {
  return window['go']['app']['App']['ListInventoryItems']();
}

export function ListItemCategories() {
  return window['go']['app']['App']['ListItemCategories']();
}

export function ListItemCategoriesForModule(arg1) {
  return window['go']['app']['App']['ListItemCategoriesForModule'](arg1);
}

export function ListItemMasters() {
  return window['go']['app']['App']['ListItemMasters']();
}

export function ListItemPrices(arg1) {
  return window['go']['app']['App']['ListItemPrices'](arg1);
}

export function ListJournalEntries(arg1, arg2) {
  return window['go']['app']['App']['ListJournalEntries'](arg1, arg2);
}

export function ListMillingOrders() {
  return window['go']['app']['App']['ListMillingOrders']();
}

export function ListOIVL(arg1) {
  return window['go']['app']['App']['ListOIVL'](arg1);
}

export function ListOpenPurchaseHeaders(arg1) {
  return window['go']['app']['App']['ListOpenPurchaseHeaders'](arg1);
}

export function ListPaymentMethodAccounts() {
  return window['go']['app']['App']['ListPaymentMethodAccounts']();
}

export function ListPriceGroups(arg1) {
  return window['go']['app']['App']['ListPriceGroups'](arg1);
}

export function ListProductionItems() {
  return window['go']['app']['App']['ListProductionItems']();
}

export function ListPurchaseHeaders() {
  return window['go']['app']['App']['ListPurchaseHeaders']();
}

export function ListPurchasingItems() {
  return window['go']['app']['App']['ListPurchasingItems']();
}

export function ListPurchasingLookup(arg1) {
  return window['go']['app']['App']['ListPurchasingLookup'](arg1);
}

export function ListSalesItems() {
  return window['go']['app']['App']['ListSalesItems']();
}

export function ListSalesOrders() {
  return window['go']['app']['App']['ListSalesOrders']();
}

export function ListSpecialPrices(arg1) {
  return window['go']['app']['App']['ListSpecialPrices'](arg1);
}

export function ListSuppliers(arg1) {
  return window['go']['app']['App']['ListSuppliers'](arg1);
}

export function ListSuppliersWithWHT(arg1) {
  return window['go']['app']['App']['ListSuppliersWithWHT'](arg1);
}

export function ListUoMGroups() {
  return window['go']['app']['App']['ListUoMGroups']();
}

export function ListUoMMasters() {
  return window['go']['app']['App']['ListUoMMasters']();
}

export function ListUsers() {
  return window['go']['app']['App']['ListUsers']();
}

export function ListWHTEntries(arg1, arg2) {
  return window['go']['app']['App']['ListWHTEntries'](arg1, arg2);
}

export function ListWarehouses() {
  return window['go']['app']['App']['ListWarehouses']();
}

export function ListWorkOrders() {
  return window['go']['app']['App']['ListWorkOrders']();
}

export function Login(arg1) {
  return window['go']['app']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function PostManualJournalEntry(arg1) {
  return window['go']['app']['App']['PostManualJournalEntry'](arg1);
}

export function PreviewMasterDataImport(arg1) {
  return window['go']['app']['App']['PreviewMasterDataImport'](arg1);
}

export function RejectSupplier(arg1) {
  return window['go']['app']['App']['RejectSupplier'](arg1);
}

export function ReleaseWorkOrder(arg1) {
  return window['go']['app']['App']['ReleaseWorkOrder'](arg1);
}

export function ReverseJournalEntry(arg1) {
  return window['go']['app']['App']['ReverseJournalEntry'](arg1);
}

export function RunDepreciation(arg1) {
  return window['go']['app']['App']['RunDepreciation'](arg1);
}

export function SetPermissions(arg1) {
  return window['go']['app']['App']['SetPermissions'](arg1);
}

export function StartMillingOrder(arg1) {
  return window['go']['app']['App']['StartMillingOrder'](arg1);
}

export function SubmitSalesOrder(arg1) {
  return window['go']['app']['App']['SubmitSalesOrder'](arg1);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['app']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateFarmSetting(arg1, arg2) {
  return window['go']['app']['App']['UpdateFarmSetting'](arg1, arg2);
}

export function UpdateFarmSettings(arg1) {
  return window['go']['app']['App']['UpdateFarmSettings'](arg1);
}

export function UpdateFixedAsset(arg1, arg2) {
  return window['go']['app']['App']['UpdateFixedAsset'](arg1, arg2);
}

export function UpdateGLAccount(arg1, arg2) {
  return window['go']['app']['App']['UpdateGLAccount'](arg1, arg2);
}

export function UpdateItemCategory(arg1, arg2) {
  return window['go']['app']['App']['UpdateItemCategory'](arg1, arg2);
}

export function UpdateItemMaster(arg1, arg2) {
  return window['go']['app']['App']['UpdateItemMaster'](arg1, arg2);
}

export function UpdateOITWMinMax(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateOITWMinMax'](arg1, arg2, arg3, arg4);
}

export function UpdatePriceGroup(arg1, arg2) {
  return window['go']['app']['App']['UpdatePriceGroup'](arg1, arg2);
}

export function UpdateSalesOrder(arg1, arg2) {
  return window['go']['app']['App']['UpdateSalesOrder'](arg1, arg2);
}

export function UpdateSupplier(arg1, arg2) {
  return window['go']['app']['App']['UpdateSupplier'](arg1, arg2);
}

export function UpdateUoMGroup(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateUoMGroup'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateUoMMaster(arg1, arg2) {
  return window['go']['app']['App']['UpdateUoMMaster'](arg1, arg2);
}

export function UpdateUser(arg1) {
  return window['go']['app']['App']['UpdateUser'](arg1);
}

export function UpdateWarehouse(arg1, arg2) {
  return window['go']['app']['App']['UpdateWarehouse'](arg1, arg2);
}

export function UpsertAccountDetermination(arg1) {
  return window['go']['app']['App']['UpsertAccountDetermination'](arg1);
}

export function UpsertBOM(arg1) {
  return window['go']['app']['App']['UpsertBOM'](arg1);
}

export function UpsertItemPrice(arg1) {
  return window['go']['app']['App']['UpsertItemPrice'](arg1);
}

export function UpsertItemUoMPrice(arg1) {
  return window['go']['app']['App']['UpsertItemUoMPrice'](arg1);
}

export function UpsertPaymentMethodAccount(arg1) {
  return window['go']['app']['App']['UpsertPaymentMethodAccount'](arg1);
}

export function UpsertPriceGroupItem(arg1) {
  return window['go']['app']['App']['UpsertPriceGroupItem'](arg1);
}

export function UpsertSpecialPrice(arg1) {
  return window['go']['app']['App']['UpsertSpecialPrice'](arg1);
}

export function VoidSalesOrder(arg1) {
  return window['go']['app']['App']['VoidSalesOrder'](arg1);
}
