// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {models} from '../models';
import {flocks} from '../models';
import {operations} from '../models';

export function AddBodyWeightLog(arg1:number,arg2:string,arg3:number,arg4:number,arg5:number,arg6:string):Promise<handlers.Response>;

export function CancelAPInvoice(arg1:number):Promise<handlers.Response>;

export function CancelARInvoice(arg1:number):Promise<handlers.Response>;

export function CancelDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function ChangePassword(arg1:handlers.ChangePasswordRequest):Promise<handlers.Response>;

export function ConfirmDeliveryOrder(arg1:number):Promise<handlers.Response>;

export function ConfirmDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function CreateAPInvoice(arg1:handlers.CreateAPInvoiceRequest):Promise<handlers.Response>;

export function CreateAPPayment(arg1:handlers.CreateAPPaymentRequest):Promise<handlers.Response>;

export function CreateARInvoice(arg1:handlers.CreateARInvoiceRequest):Promise<handlers.Response>;

export function CreateBackup():Promise<handlers.Response>;

export function CreateCollection(arg1:handlers.CreateCollectionRequest):Promise<handlers.Response>;

export function CreateCustomer(arg1:models.Customer):Promise<handlers.Response>;

export function CreateDeliveryOrder(arg1:handlers.CreateDeliveryOrderRequest):Promise<handlers.Response>;

export function CreateDeliveryReceipt(arg1:handlers.CreateDeliveryReceiptRequest):Promise<handlers.Response>;

export function CreateFlock(arg1:flocks.CreateFlockRequest):Promise<handlers.Response>;

export function CreateGLAccount(arg1:handlers.CreateGLAccountRequest):Promise<handlers.Response>;

export function CreateItemCategory(arg1:models.ItemCategory):Promise<handlers.Response>;

export function CreateItemMaster(arg1:models.ItemMaster):Promise<handlers.Response>;

export function CreatePriceGroup(arg1:models.PriceGroup):Promise<handlers.Response>;

export function CreatePurchase(arg1:models.Purchase):Promise<handlers.Response>;

export function CreateSalesOrder(arg1:handlers.CreateSalesOrderRequest):Promise<handlers.Response>;

export function CreateSupplier(arg1:models.Supplier):Promise<handlers.Response>;

export function CreateUser(arg1:handlers.CreateUserRequest):Promise<handlers.Response>;

export function CreateVaccineSchedule(arg1:number,arg2:string,arg3:string,arg4:string):Promise<handlers.Response>;

export function DeleteAccountDetermination(arg1:number):Promise<handlers.Response>;

export function DeleteBackup(arg1:string):Promise<handlers.Response>;

export function DeleteBodyWeightLog(arg1:number):Promise<handlers.Response>;

export function DeleteCustomer(arg1:number):Promise<handlers.Response>;

export function DeleteGLAccount(arg1:number):Promise<handlers.Response>;

export function DeleteItemCategory(arg1:number):Promise<handlers.Response>;

export function DeleteItemMaster(arg1:number):Promise<handlers.Response>;

export function DeletePriceGroup(arg1:number):Promise<handlers.Response>;

export function DeleteSupplier(arg1:number):Promise<handlers.Response>;

export function DeleteUser(arg1:number):Promise<handlers.Response>;

export function GetAPInvoice(arg1:number):Promise<handlers.Response>;

export function GetAPPayment(arg1:number):Promise<handlers.Response>;

export function GetARAgingReport():Promise<handlers.Response>;

export function GetARInvoice(arg1:number):Promise<handlers.Response>;

export function GetAnalytics(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetAuditLogs(arg1:number):Promise<handlers.Response>;

export function GetBalanceSheet(arg1:string):Promise<handlers.Response>;

export function GetBodyWeightData(arg1:number):Promise<handlers.Response>;

export function GetChartOfAccounts():Promise<handlers.Response>;

export function GetCollection(arg1:number):Promise<handlers.Response>;

export function GetCurrentUser():Promise<handlers.Response>;

export function GetCustomer(arg1:number):Promise<handlers.Response>;

export function GetDailyLog(arg1:number):Promise<handlers.Response>;

export function GetDashboard():Promise<handlers.Response>;

export function GetDeliveryOrder(arg1:number):Promise<handlers.Response>;

export function GetDeliveryReceipt(arg1:number):Promise<handlers.Response>;

export function GetEggInventory():Promise<handlers.Response>;

export function GetFarmSettings():Promise<handlers.Response>;

export function GetFlock(arg1:number):Promise<handlers.Response>;

export function GetFlocks():Promise<handlers.Response>;

export function GetGLAccount(arg1:number):Promise<handlers.Response>;

export function GetGrowerLog(arg1:number):Promise<handlers.Response>;

export function GetHouseHistory(arg1:number):Promise<handlers.Response>;

export function GetItemCategory(arg1:number):Promise<handlers.Response>;

export function GetItemMaster(arg1:number):Promise<handlers.Response>;

export function GetJournalEntry(arg1:number):Promise<handlers.Response>;

export function GetLayerHouses():Promise<handlers.Response>;

export function GetPnL(arg1:string,arg2:string):Promise<handlers.Response>;

export function GetPostingEvents():Promise<handlers.Response>;

export function GetPriceGroup(arg1:number):Promise<handlers.Response>;

export function GetPurchase(arg1:number):Promise<handlers.Response>;

export function GetSalesOrder(arg1:number):Promise<handlers.Response>;

export function GetSupplier(arg1:number):Promise<handlers.Response>;

export function ListAPInvoices(arg1:any,arg2:string):Promise<handlers.Response>;

export function ListAPPayments():Promise<handlers.Response>;

export function ListARInvoices(arg1:any,arg2:string):Promise<handlers.Response>;

export function ListAccountDeterminations():Promise<handlers.Response>;

export function ListBackups():Promise<handlers.Response>;

export function ListCollections():Promise<handlers.Response>;

export function ListCustomers(arg1:boolean):Promise<handlers.Response>;

export function ListDeliveryOrders(arg1:number):Promise<handlers.Response>;

export function ListDeliveryReceipts(arg1:number):Promise<handlers.Response>;

export function ListFeedStocks():Promise<handlers.Response>;

export function ListGLAccounts():Promise<handlers.Response>;

export function ListInventory():Promise<handlers.Response>;

export function ListItemCategories():Promise<handlers.Response>;

export function ListItemMasters():Promise<handlers.Response>;

export function ListJournalEntries(arg1:string,arg2:number):Promise<handlers.Response>;

export function ListPaymentMethodAccounts():Promise<handlers.Response>;

export function ListPriceGroups(arg1:boolean):Promise<handlers.Response>;

export function ListPurchases():Promise<handlers.Response>;

export function ListSalesOrders():Promise<handlers.Response>;

export function ListSuppliers(arg1:boolean):Promise<handlers.Response>;

export function ListUsers():Promise<handlers.Response>;

export function ListVaccineSchedules(arg1:number):Promise<handlers.Response>;

export function Login(arg1:handlers.LoginRequest):Promise<handlers.Response>;

export function Logout():Promise<handlers.Response>;

export function MarkVaccineComplete(arg1:number):Promise<handlers.Response>;

export function PostManualJournalEntry(arg1:handlers.ManualJERequest):Promise<handlers.Response>;

export function RecordDailyLog(arg1:operations.RecordDailyLogRequest):Promise<handlers.Response>;

export function RecordGrowerLog(arg1:operations.RecordGrowerLogRequest):Promise<handlers.Response>;

export function RetireFlock(arg1:flocks.RetireFlockRequest):Promise<handlers.Response>;

export function ReverseJournalEntry(arg1:number):Promise<handlers.Response>;

export function SetPermissions(arg1:handlers.SetPermissionsRequest):Promise<handlers.Response>;

export function TransferFlock(arg1:flocks.TransferFlockRequest):Promise<handlers.Response>;

export function UpdateBodyWeightLog(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<handlers.Response>;

export function UpdateCustomer(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateDailyLog(arg1:number,arg2:operations.RecordDailyLogRequest):Promise<handlers.Response>;

export function UpdateFarmSetting(arg1:string,arg2:string):Promise<handlers.Response>;

export function UpdateFarmSettings(arg1:Record<string, string>):Promise<handlers.Response>;

export function UpdateFlock(arg1:flocks.UpdateFlockRequest):Promise<handlers.Response>;

export function UpdateGLAccount(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateGrowerLog(arg1:number,arg2:operations.RecordGrowerLogRequest):Promise<handlers.Response>;

export function UpdateItemCategory(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateItemMaster(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdatePriceGroup(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdatePurchase(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateSupplier(arg1:number,arg2:Record<string, any>):Promise<handlers.Response>;

export function UpdateUser(arg1:handlers.UpdateUserRequest):Promise<handlers.Response>;

export function UpsertAccountDetermination(arg1:handlers.UpsertAccountDeterminationRequest):Promise<handlers.Response>;

export function UpsertPaymentMethodAccount(arg1:handlers.UpsertPaymentMethodAccountRequest):Promise<handlers.Response>;

export function UpsertPriceGroupItem(arg1:handlers.UpsertPriceGroupItemRequest):Promise<handlers.Response>;

export function VoidSalesOrder(arg1:number):Promise<handlers.Response>;
